### ISSUE TITLE
AngularJS Best Practices

### ISSUE THREAD

**Issue by SStachoPGH** [eightdotthree/eightdotthree.net#6]
Use the controllerAs syntax to pass in your context.

Example:

JavaScript

angular.module('eightdotthreeApp', ['EightdotthreeController'])

.controller('EightdotthreeController', function (Instagram)  {

```
var ctrl = this;

ctrl.photos = [];
ctrl.have = [];
ctrl.loading = true;
ctrl.loadedIndex = 0;
ctrl.nextPageUrl = '';

ctrl.getFirstPage = function() {
    ctrl.loading = true;
    var endpoint = Instagram.buildEndpoint('/users/media/recent/');
    Instagram.get(endpoint, ctrl.processFeed);
};
```

});

HTML

<body data-ng-controller="EightdotthreeController as cont">

```
<!-- More code here -->

<ul class="clearfix">
    <li data-ng-repeat="p in cont.photos">
        <!-- Do something here... -->
    </li>
</ul>

<!-- More code here -->
```

</body>

**Comment by SStachoPGH** [comment]
Just as well, make sure to pass angular, a global variable, into your enclosure.

(function (angular, window) {

```
'use strict';
```

}(window.angular, window));

**Comment by eightdotthree** [comment]
I found [this page helpful](http://toddmotto.com/opinionated-angular-js-styleguide-for-teams/), leaving for future reference.
